apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: v5.49.0
  releaseName: argocd
  namespace: argocd
  includeCRDs: true
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.13.2
  namespace: cert-manager
  includeCRDs: true
- name: base
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.18.0
  namespace: istio-system
  includeCRDs: true
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.18.0
  namespace: istio-ingress
  includeCRDs: true
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.18.0
  namespace: istio-system
  includeCRDs: true
- name: keycloakx
  repo: https://codecentric.github.io/helm-charts
  version: 2.3.0
  namespace: keycloak
  includeCRDs: true
- name: kiali-operator
  repo: https://kiali.org/helm-charts
  version: 1.70.0
  namespace: kiali-operator
  includeCRDs: true
# todo: mysql-operator
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  version: 6.23.1
  namespace: oauth2-proxy
  includeCRDs: true
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 48.1.1
  namespace: kube-prometheus
  includeCRDs: true
# todo: lgtm-distributed
#- name: lgtm-distributed
#  repo: https://grafana.github.io/helm-charts
#  version: 1.0.1
#  namespace: lgtm
#  includeCRDs: true
- name: promtail
  repo: https://grafana.github.io/helm-charts
  version: 6.11.5
  namespace: promtail
  includeCRDs: true
- name: rook-ceph
  repo: https://charts.rook.io/release
  version: v1.13.2
  namespace: rook-ceph
  includeCRDs: true
- name: strimzi-kafka-operator
  repo: https://strimzi.io/charts/
  version: 0.35.1
  namespace: kafka
  includeCRDs: true
